name: "Twitter List Sync"
description: "Sync your Twitter followers/following to Lists"
author: "Anand Chowdhary <https://github.com/AnandChowdhary>"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "users"
  color: "blue"
- name: Twitter List Sync
  uses: AnandChowdhary/twitter-list-sync@v1.1.0
